--[[
Type: Custom,
Event Type: Event,
Event(s): OPTIONS,JOEGNIS_CLASS_WA_INIT,PLAYER_ENTERING_WORLD,PLAYER_SPECIALIZATION_CHANGED,UPDATE_SHAPESHIFT_FORM,PLAYER_TALENT_UPDATE,PLAYER_PVP_TALENT_UPDATE,PLAYER_LEVEL_UP
]]
function(event)
    local CLASS = JOEGNIS_CLASS_WA.CLASS
    local MAIN_GROUP = "Main - JWA - " .. CLASS
    local SECOND_GROUP = "Second - JWA - " .. CLASS
    local TERTIARY1_GROUP = "Tertiary1 - JWA - " .. CLASS
    local TERTIARY2_GROUP = "Tertiary2 - JWA - " .. CLASS
    local QUATERNARY1_GROUP = "Quaternary1 - JWA - " .. CLASS
    local QUATERNARY2_GROUP = "Quaternary2 - JWA - " .. CLASS

    JOEGNIS_CLASS_WA.styleIconsInGroup(
        MAIN_GROUP,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_MAIN].width,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_MAIN].height
    )
    JOEGNIS_CLASS_WA.styleIconsInGroup(
        SECOND_GROUP,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_SECOND].width,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_SECOND].height
    )
    JOEGNIS_CLASS_WA.styleIconsInGroup(
        TERTIARY1_GROUP,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_TERTIARY1].width,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_TERTIARY1].height
    )
    JOEGNIS_CLASS_WA.styleIconsInGroup(
        TERTIARY2_GROUP,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_TERTIARY2].width,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_TERTIARY2].height
    )
    JOEGNIS_CLASS_WA.styleIconsInGroup(
        QUATERNARY1_GROUP,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_QUATERNARY1].width,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_QUATERNARY1].height
    )
    JOEGNIS_CLASS_WA.styleIconsInGroup(
        QUATERNARY2_GROUP,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_QUATERNARY2].width,
        JOEGNIS_CLASS_WA.config[JOEGNIS_CLASS_WA.CONFIG_GROUP_QUATERNARY2].height
    )
end
